### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by csarven**
Add properties and classes related to expressing "changelog" information available in technical reports, e.g., change subject, correction or change class (see below), and human-readable statement.

Changelogs are marked in documents such as [Solid Protocol](https://solidproject.org/TR/protocol#changelog), [Solid Notifications Protocol](https://solidproject.org/TR/notifications-protocol#changelog), [Web Access Control](https://solidproject.org/TR/wac#changelog). These reports include "a summary of editorial, substantive, and registry changes are classified using the W3C Process Document [Classes of Changes](https://www.w3.org/Consortium/Process/#correction-classes)".

A human-readable view of an example [changelog of Solid Protocol, v0.11](https://solidproject.org/TR/2024/protocol-20240512#changelog):

image

Example usage in Turtle connecting document, a particular requirement, with changelog information about that requirement:

```turtle
@prefix spec: <http://www.w3.org/ns/spec#> .
@prefix : <https://solidproject.org/TR/2024/protocol-20240512#> .

<https://solidproject.org/TR/2024/protocol-20240512>
    spec:changelog :changelog ;
    spec:requirement :server-content-type-includes .

:changelog
    spec:change :d18392b9-8ffc-4264-a5a2-10e2da6fac32 .

:d18392b9-8ffc-4264-a5a2-10e2da6fac32
    a spec:Change ;
    spec:changeClass <https://www.w3.org/Consortium/Process/#class-4> ;
    spec:changeSubject :server-content-type-includes ;
    spec:statement "Add requirement for server to include Content-Type header field in messages with content."@en .

:server-content-type-includes
    spec:requirementLevel spec:MUST ;
    spec:requirementSubject :Server ;
    spec:statement "Server MUST generate a Content-Type header field in a message that contains content."@en .
```

Live SPARQL Query selecting changelog information across technical reports:

https://sparql.org/sparql?query=%0D%0APREFIX+spec%3A+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fspec%23%3E%0D%0ASELECT+%3Fdocument+%3Fchange+%3FchangeClass+%3FchangeSubject+%3Fstatement%0D%0AFROM+%0D%0A%3Chttp%3A%2F%2Frdf.greggkellogg.net%2Fdistiller%3Fcommand%3Dserialize%26format%3Drdfa%26output_format%3Dturtle%26url%3Dhttps%3A%252F%252Fsolidproject.org%252FTR%252Fprotocol%26raw%3E%0D%0AFROM+%0D%0A%3Chttp%3A%2F%2Frdf.greggkellogg.net%2Fdistiller%3Fcommand%3Dserialize%26format%3Drdfa%26output_format%3Dturtle%26url%3Dhttps%3A%252F%252Fsolidproject.org%252FTR%252Fwac%26raw%3E%0D%0AFROM+%0D%0A%3Chttp%3A%2F%2Frdf.greggkellogg.net%2Fdistiller%3Fcommand%3Dserialize%26format%3Drdfa%26output_format%3Dturtle%26url%3Dhttps%3A%252F%252Fsolidproject.org%252FTR%252Fnotifications-protocol%26raw%3E%0D%0AFROM+%0D%0A%3Chttp%3A%2F%2Frdf.greggkellogg.net%2Fdistiller%3Fcommand%3Dserialize%26format%3Drdfa%26output_format%3Dturtle%26url%3Dhttps%3A%252F%252Fsolidproject.org%252FED%252Fqa%26raw%3E%0D%0AFROM+%0D%0A%3Chttp%3A%2F%2Frdf.greggkellogg.net%2Fdistiller%3Fcommand%3Dserialize%26format%3Drdfa%26output_format%3Dturtle%26url%3Dhttps%3A%252F%252Fsolid.github.io%252Fwebid-profile%252F%26raw%3E%0D%0AWHERE%7B%0D%0A++%3Fdocument+spec%3Achangelog+%5B%0D%0A++++spec%3Achange+%3Fchange+%3B%0D%0A++%5D+.%0D%0A++%3Fchange%0D%0A++++spec%3AchangeClass+%3FchangeClass+%3B%0D%0A++++spec%3AchangeSubject+%3FchangeSubject+%3B%0D%0A++++spec%3Astatement+%3Fstatement+.%0D%0A%7D%0D%0AORDER+BY+%3Fdocument+%3FchangeClass+%3FchangeSubject&default-graph-uri=&output=xml&stylesheet=%2Fxml-to-html.xsl

An application (e.g., [dokieli](https://dokie.li/)) making use of the changelog information by incorporating into a *Conformance Requirements and Test Coverage* table where a requirement URI is matched with a change subject URI:

image

### CODE REVIEW

**Review by elf-pavlik — APPROVED** [review]
I think it is still missing specific subclasses for the `spec:Change`, looking at the examples, it probably needs `spec:Addition`, `spec:Removal` and `spec:Amendment`

**Review by kjetilk — APPROVED** [review]
Yes, I think this can go in in the present form. 

I'm also thinking along the same lines as @elf-pavlik that the orthogonal concern of additions, removals, and so on is needed. However, that was in the http://ontologi.es/doap-changeset# ontology that @tobyink made back in the day, and that I used a lot. It doesn't seem to resolve anymore, so I guess it isn't maintained. 

It is broader than spec, so I suppose it should be in a different vocab, perhaps DOAP would be a better place for it.

**Comment by csarven** [comment]
@pchampin Can you please update http://www.w3.org/ns/spec with https://raw.githubusercontent.com/solid/vocab/main/spec.ttl

**Comment by pchampin** [comment]
done

**Pull request merged**
